### ISSUE TITLE
Please tag release notes so we can get Github notifications on new releases

### ISSUE THREAD

**Issue by pdecat** [datastax/release-notes#12]
Hi,

it would be awesome if you could create git tags when publishing new release notes for each product.

This would allow users like me to specifically subscribe for Github release notifications (which also notify new tags):

![image](https://user-images.githubusercontent.com/318490/108350487-8dc65680-71e4-11eb-8949-3050fb734a03.png)

E.g. this commit https://github.com/datastax/release-notes/commit/46b947de1f8a32fb7e7dd16fa99460a231bd5165
could have been tagged `OpsCenter-6.8.11` or something like that.

**Comment by tiagomlalves** [comment]
Hi @pdecat , it's been a while since you posted this issue. We're using this repo to store the release notes for different products. Is this still relevant to you? Wouldn't add tags for each of them (i.e. `dse-x.y.z`, `opscenter-x.y.z`, etc.) make it a bit confusing?

**Comment by pdecat** [comment]
Hi, I wouldn't find it that much confusing, the most important aspect to me being it would help getting notifications about new releases. Unless there are already other means to be notified about new releases.

**Comment by tiagomlalves** [comment]
@pdecat unfortunately we don't have another way to publicly announce new versions. I'll ping our docs team to know if they have some ideas. I'll propose your suggestion hoping we can use it for the time being. I'll leave this issue open until we find a solution.

**Comment by tiagomlalves** [comment]
@pdecat just a heads-up that from now on, we'll be tagging this repository together with the release of new product / publishing release notes. Thanks again for suggest it.

**Comment by pdecat** [comment]
Awesome, thanks!
