### ISSUE TITLE
6.7 EOL Timeline

### ISSUE THREAD

**Issue by chancancode** [datastax/release-notes#39]
Hi, can you confirm the EOL timeline for DSE 6.7? In the release notes for 6.7.15, a note was added to indicate an imminent EOL for DSE 6.7. However, the text linked to a page that mentioned a _minimum_ EOL date of mid next year, as well as the general policy of maintaining the packages for at least 36 months. Can you clarify?

**Comment by chancancode** [comment]
See https://github.com/datastax/release-notes/blob/master/DSE_6.7_Release_Notes.md and https://www.datastax.com/legal/supported-software

**Comment by chancancode** [comment]
In addition, [this page](https://docs.datastax.com/en/dse/6.7/dse-admin/datastax_enterprise/releaseNotes/RNdse.html) has a banner on top that said 6.7 will be EOL by December 2022, so I am inclined to think the note in the release notes was a typo?

**Comment by chancancode** [comment]
Hello @nicoloboschi @qzg @tiagomlalves can we have a confirmation on this?

**Comment by tiagomlalves** [comment]
Hi @chancancode. Sorry for the late reply. 
The correct EOL date for 6.7 is in: https://www.datastax.com/legal/supported-software

I'll fix the DSE 6.8 Release Notes - thanks for noticing it.

**Comment by chancancode** [comment]
Thanks you, appreciate it!

**Comment by tiagomlalves** [comment]
Issue addressed in [PR #40](https://github.com/datastax/release-notes/pull/40) and changes merged. Once again, thanks for the heads-up.
